"""add_value_columns_to_attribute_values

Revision ID: 7193426fefa6
Revises: 3075f9f2623b
Create Date: 2025-01-16 17:27:44.092548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7193426fefa6'
down_revision: Union[str, None] = '3075f9f2623b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_users')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_id')

    op.drop_table('notifications')
    with op.batch_alter_table('product_attribute_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_value', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_attribute_values', schema=None) as batch_op:
        batch_op.drop_column('display_value')
        batch_op.drop_column('value')

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('notifications_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', name='notificationstatus'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_id', ['id'], unique=False)

    op.create_table('notification_users',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='notification_users_notification_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_users_user_id_fkey')
    )
    # ### end Alembic commands ###
